version: "3"
services:
  app:
    container_name: my
    restart: always
    command: ["npm", "start"]
    volumes:
      - ./server/:/app
#      - /app/node_modules
    build: ./server
    ports:
      - 8082:3001
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
    - "27018:27017"
    
